<?php
use \Cmatrix\Kernel as kernel;
use \Cmatrix\Db as db;

include '../../../../../../defs.php';
include '../../../../../../common.php';

$Connect2 = db\Connect::get('dbv2');
$Connect4 = db\Connect::get();

// --- описание таблиц v2
$Arr2 = [
    // Фреза концевая
    'FrMonKonc' => [
        'tables' => [
            'mz_tl_FrMonKonc AS tool' => [ 'mz_tl_Kind AS kind ON kind.id=tool.kind' ],
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'CAST(NULL AS REAL) AS d',
            'tool.d1',
            'tool.d2',
            'tool.d3',
            'tool.r',
            'tool.cf',
            'tool.l1',
            'tool.l2',
            'CAST(NULL AS REAL) AS l3',
            'CAST(NULL AS REAL) AS l4',
            'tool.ap',
            'CAST(NULL AS REAL) AS ar',
            'tool.z',
            'tool.purpose',
            'kind.label AS kind',
            'CAST(NULL AS REAL) AS angle',
            'NULL AS thread',
            'CAST(NULL AS REAL) AS pitch',
            'CAST(NULL AS REAL) AS pmin',
            'CAST(NULL AS REAL) AS pmax',
            'NULL AS adin',
            'CAST(NULL AS REAL) AS adimin',
            'CAST(NULL AS REAL) AS adimax',
            'NULL AS adout',
            'CAST(NULL AS VARCHAR) AS tpl',
            'CAST(NULL AS VARCHAR) AS spl',
            'CAST(NULL AS VARCHAR) AS fpl',
            'CAST(NULL AS BOOL) AS coolin',
            'CAST(NULL AS VARCHAR) AS t',
            'CAST(NULL AS REAL) AS kr',
            'CAST(NULL AS REAL) AS f1',
            'CAST(NULL AS REAL) AS dmin',
            'CAST(NULL AS BOOL) AS purpout',
            'CAST(NULL AS BOOL) AS purpin',
            'CAST(NULL AS VARCHAR) AS purptok',
            'CAST(NULL AS TEXT) AS inserts',
            'CAST(NULL AS INTEGER) AS icount',
            'CAST(NULL AS REAL) AS regmin',
            'CAST(NULL AS REAL) AS regmax',
            'CAST(NULL AS VARCHAR) AS tooltype',
            'CAST(NULL AS VARCHAR) AS cooltype',
            'CAST(NULL AS VARCHAR) AS m',
            'CAST(NULL AS VARCHAR) AS orient',
        ],
    ],
    
    // Фреза сферическая
    'FrMonSfer' => [
        'tables' => [
            'mz_tl_FrMonSfer AS tool' => [ 'mz_tl_Kind AS kind ON kind.id=tool.kind' ],
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'tool.d1',
            'tool.d2',
            'tool.d3',
            'NULL AS r',
            'NULL AS cf',
            'tool.l1',
            'tool.l2',
            'NULL AS l3',
            'NULL AS l4',
            'tool.ap',
            'NULL AS ar',
            'tool.z',
            'tool.purpose',
            'kind.label AS kind',
            'NULL AS angle',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'NULL AS adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'NULL AS adout',
            'NULL AS tpl',
            'NULL AS spl',
            'NULL AS fpl',
            'NULL AS coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Фреза грибковая монолитная
    'FrMonGrib' => [
        'tables' => [
            'mz_tl_FrMonGrib AS tool' => [ 'mz_tl_Kind AS kind ON kind.id=tool.kind' ],
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'tool.d1',
            'tool.d2',
            'NULL AS d3',
            'NULL AS r',
            'NULL AS cf',
            'tool.l1',
            'tool.l2',
            'NULL AS l3',
            'NULL AS l4',
            'tool.ap',
            'NULL AS ar',
            'tool.z',
            'purpose',
            'kind.label AS kind',
            'NULL AS angle',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'NULL AS adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'NULL AS adout',
            'NULL AS tpl',
            'NULL AS spl',
            'NULL AS fpl',
            'NULL AS coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Резьбофреза монолитная
    'FrMonRez' => [
        'tables' => [
            'mz_tl_FrMonRez AS tool' => [ 'mz_tl_Kind AS kind ON kind.id=tool.kind' ],
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'tool.d1',
            'tool.d2',
            'NULL AS d3',
            'NULL AS r',
            'NULL AS cf',
            'tool.l1',
            'NULL AS l2',
            'NULL AS l3',
            'NULL AS l4',
            'tool.ap',
            'NULL AS ar',
            'tool.z',
            'purpose',
            'kind.label AS kind',
            'NULL AS angle',
            'tool.thread',
            'tool.pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'NULL AS adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'NULL AS adout',
            'NULL AS tpl',
            'NULL AS spl',
            'NULL AS fpl',
            'NULL AS coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Фреза дисковая монолитная
    'FrMonDisk' => [
        'tables' => [
            'mz_tl_FrMonDisk AS tool' => [ 'mz_tl_Kind AS kind ON kind.id=tool.kind', 'mz_tl_MillDiskPurpose AS purpose ON purpose.id=tool.purpose'],
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'tool.d1',
            'tool.d2',
            'NULL AS d3',
            'tool.r',
            'tool.cf',
            'NULL AS l1',
            'NULL AS l2',
            'NULL AS l3',
            'NULL AS l4',
            'tool.ap',
            'tool.ar',
            'tool.z',
            'lower(purpose.name)',
            'kind.label AS kind',
            'NULL AS angle',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'NULL AS adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'NULL AS adout',
            'NULL AS tpl',
            'NULL AS spl',
            'NULL AS fpl',
            'NULL AS coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Фасочник монолитный
    'FrMonFas' => [
        'tables' => [
            'mz_tl_FrMonFas AS tool' => [ 'mz_tl_Kind AS kind ON kind.id=tool.kind' ],
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'tool.d1',
            'tool.d2',
            'tool.d3',
            'NULL AS r',
            'NULL AS cf',
            'tool.l1',
            'tool.l2',
            'NULL AS l3',
            'NULL AS l4',
            'tool.ap',
            'NULL AS ar',
            'tool.z',
            'tool.purpose',
            'kind.label AS kind',
            'tool.ang AS angle',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'NULL AS adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'NULL AS adout',
            'NULL AS tpl',
            'NULL AS spl',
            'NULL AS fpl',
            'NULL AS coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Головка фрезерная с пластинами
    'FrGolPl' => [
        'tables' => [
            'mz_tl_FrGolPl AS tool' => [ 'mz_tl_Kind AS kind ON kind.id=tool.kind' ],
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'tool.d1',
            'tool.d2',
            'NULL AS d3',
            'NULL AS r',
            'NULL AS cf',
            'tool.l1',
            'NULL AS l2',
            'NULL AS l3',
            'NULL AS l4',
            'tool.ap',
            'NULL AS ar',
            'tool.z',
            'NULL AS purpose',
            'kind.label AS kind',
            'NULL AS angle',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'tool.adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'tool.adout',
            'NULL AS tpl',
            'NULL AS spl',
            'NULL AS fpl',
            'NULL AS coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Головка фрезерная твёрдосплавная
    'FrGolTs' => [
        'tables' => [
            'mz_tl_FrGolTs AS tool' => [ 'mz_tl_Kind AS kind ON kind.id=tool.kind' ],
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'tool.d1',
            'tool.d2',
            'NULL AS d3',
            'tool.r',
            'tool.cf',
            'tool.l1',
            'NULL AS l2',
            'NULL AS l3',
            'NULL AS l4',
            'tool.ap',
            'NULL AS ar',
            'tool.z',
            'tool.purpose',
            'kind.label AS kind',
            'NULL AS angle',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'NULL AS adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'tool.adout',
            'NULL AS tpl',
            'NULL AS spl',
            'NULL AS fpl',
            'NULL AS coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Оправка под головку
    'OprGol' => [
        'tables' => [
            'mz_tl_OprGol AS tool' => null,
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'NULL AS d1',
            'tool.d2',
            'tool.d3',
            'NULL AS r',
            'NULL AS cf',
            'tool.l1',
            'tool.l2',
            'NULL AS l3',
            'NULL AS l4',
            'NULL AS ap',
            'NULL AS ar',
            'NULL AS z',
            'NULL AS purpose',
            'NULL AS kind',
            'NULL AS angle',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'tool.adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'tool.adout',
            'NULL AS tpl',
            'NULL AS spl',
            'NULL AS fpl',
            'NULL AS coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Фреза корпусная
    'FrKorp' => [
        'tables' => [
            'mz_tl_FrKorp AS tool' => [ 'mz_tl_Kind AS kind ON kind.id=tool.kind' ],
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'tool.d1',
            'tool.d2',
            'NULL AS d3',
            'NULL AS r',
            'NULL AS cf',
            'tool.l1',
            'NULL AS l2',
            'NULL AS l3',
            'NULL AS l4',
            'tool.ap',
            'NULL AS ar',
            'tool.z',
            'NULL AS purpose',
            'kind.label AS kind',
            'NULL AS angle',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'tool.adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'tool.adout',
            'NULL AS tpl',
            'NULL AS spl',
            'NULL AS fpl',
            'NULL AS coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Фреза грибковая сборная
    'FrSborGrib' => [
        'tables' => [
            'mz_tl_FrSborGrib AS tool' => [ 'mz_tl_Kind AS kind ON kind.id=tool.kind', 'mz_tl_MillFungoidPurpose AS purpose ON purpose.id=tool.purpose' ],
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'tool.d1',
            'tool.d2',
            'tool.d3',
            'NULL AS r',
            'NULL AS cf',
            'tool.l1',
            'tool.l2',
            'NULL AS l3',
            'NULL AS l4',
            'tool.ap',
            'CAST(tool.ar AS REAL) AS ar',
            'tool.z',
            'lower(purpose.name) AS purpose',
            'kind.label AS kind',
            'NULL AS angle',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'tool.adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'tool.adout',
            'NULL AS tpl',
            'NULL AS spl',
            'NULL AS fpl',
            'NULL AS coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Пластина фрезерная
    'FrPl' => [
        'tables' => [
            'mz_tl_FrPl AS tool' => null,
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'NULL AS d1',
            'NULL AS d2',
            'NULL AS d3',
            'tool.r',
            'NULL AS cf',
            'NULL AS l1',
            'NULL AS l2',
            'NULL AS l3',
            'NULL AS l4',
            'NULL AS ap',
            'NULL AS ar',
            'NULL AS z',
            'tool.purpose',
            'NULL AS kind',
            'NULL AS angle',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'NULL AS adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'NULL AS adout',
            'tool.tpl',
            'tool.spl',
            'NULL AS fpl',
            'NULL AS coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Фреза дисковая сборная
    'FrSborDisk' => [
        'tables' => [
            'mz_tl_FrSborDisk AS tool' => [ 'mz_tl_Kind AS kind ON kind.id=tool.kind', 'mz_tl_MillDiskPurpose AS purpose ON purpose.id=tool.purpose' ],
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'tool.d1',
            'tool.d2',
            'NULL AS d3',
            'NULL AS r',
            'NULL AS cf',
            'NULL AS l1',
            'NULL AS l2',
            'NULL AS l3',
            'NULL AS l4',
            'tool.ap',
            'tool.ar',
            'tool.z',
            'lower(purpose.name) AS purpose',
            'kind.label AS kind',
            'NULL AS angle',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'tool.adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'tool.adout',
            'NULL AS tpl',
            'NULL AS spl',
            'NULL AS fpl',
            'NULL AS coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Фасочник сборный
    'FrSborFas' => [
        'tables' => [
            'mz_tl_FrSborFas AS tool' => [ 'mz_tl_Kind AS kind ON kind.id=tool.kind' ],
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'tool.d1',
            'tool.d2',
            'tool.d3',
            'NULL AS r',
            'NULL AS cf',
            'tool.l1',
            'tool.l2',
            'tool.l3',
            'NULL AS l4',
            'tool.ap',
            'NULL AS ar',
            'tool.z',
            'tool.purpose',
            'kind.label AS kind',
            'tool.ang AS angel',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'tool.adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'tool.adout',
            'NULL AS tpl',
            'NULL AS spl',
            'NULL AS fpl',
            'NULL AS coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Корпус фрезы канавочной
    'FrSborKanKorp' => [
        'tables' => [
            'mz_tl_FrSborKanKorp AS tool' => null,
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'NULL AS d1',
            'tool.d2',
            'tool.d3',
            'NULL AS r',
            'NULL AS cf',
            'tool.l1',
            'tool.l2',
            'NULL AS l3',
            'NULL AS l4',
            'NULL AS ap',
            'NULL AS ar',
            'NULL AS z',
            'NULL AS purpose',
            'NULL AS kind',
            'NULL AS angel',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'tool.adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'tool.adout',
            'NULL AS tpl',
            'NULL AS spl',
            'NULL AS fpl',
            'NULL AS coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Пластина канавочная
    'FrSborKanPl' => [
        'tables' => [
            'mz_tl_FrSborKanPl AS tool' => [ 'mz_tl_TcutterInsertPurpose AS purpose ON purpose.id=tool.purpose' ],
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'tool.d1',
            'NULL AS d2',
            'NULL AS d3',
            'tool.r',
            'NULL AS cf',
            'NULL AS l1',
            'NULL AS l2',
            'NULL AS l3',
            'NULL AS l4',
            'tool.ap',
            'tool.ar',
            'tool.z',
            'lower(purpose.name) AS purpose',
            'NULL AS kind',
            'NULL AS angle',
            'tool.thread',
            'NULL AS pitch',
            'tool.pmin',
            'tool.pmax',
            'NULL AS adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'NULL AS adout',
            'tool.tpl',
            'tool.spl',
            'NULL AS fpl',
            'NULL AS coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Специнструмент фрезерный // !!! нет параметров
    //'FrSpec' => [
    //],
    
    // Переточенный
    'FrPeret' => [
        'tables' => [
            'mz_tl_FrPeret AS tool' => null,
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'tool.d1',
            'tool.d2',
            'tool.d3',
            'tool.r',
            'tool.cf',
            'tool.l1',
            'tool.l2',
            'NULL AS l3',
            'NULL AS l4',
            'tool.ap',
            'NULL AS ar',
            'tool.z',
            'NULL AS purpose',
            'NULL AS kind',
            'NULL AS angle',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'NULL AS adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'NULL AS adout',
            'NULL AS tpl',
            'NULL AS spl',
            'NULL AS fpl',
            'NULL AS coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Сверло
    'OsevSverMon' => [
        'tables' => [
            'mz_tl_OsevSverMon AS tool' => null,
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'tool.d1',
            'tool.d2',
            'NULL AS d3',
            'NULL AS r',
            'NULL AS cf',
            'tool.l1',
            'NULL AS l2',
            'tool.l3',
            'NULL AS l4',
            'tool.ap',
            'NULL AS ar',
            'NULL AS z',
            'tool.purpose',
            'NULL AS kind',
            'NULL AS angel',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'NULL AS adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'NULL AS adout',
            'NULL AS tpl',
            'NULL AS spl',
            'NULL AS fpl',
            'tool.coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Развёртка
    'OsevRazv' => [
        'tables' => [
            'mz_tl_OsevRazv AS tool' => null,
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'tool.d1',
            'tool.d2',
            'NULL AS d3',
            'NULL AS r',
            'NULL AS cf',
            'tool.l1',
            'NULL AS l2',
            'tool.l3',
            'NULL AS l4',
            'tool.ap',
            'NULL AS ar',
            'NULL AS z',
            'tool.purpose',
            'NULL AS kind',
            'NULL AS angel',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'NULL AS adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'NULL AS adout',
            'NULL AS tpl',
            'NULL AS spl',
            'NULL AS fpl',
            'NULL AS coolin',
            'tool.t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Сверло сборное
    'OsevSverSbor' => [
        'tables' => [
            'mz_tl_OsevSverSbor AS tool' => null,
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'tool.d1',
            'tool.d2',
            'NULL AS d3',
            'NULL AS r',
            'NULL AS cf',
            'tool.l1',
            'NULL AS l2',
            'tool.l3',
            'NULL AS l4',
            'tool.ap',
            'NULL AS ar',
            'NULL AS z',
            'tool.purpose',
            'NULL AS kind',
            'NULL AS angel',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'NULL AS adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'NULL AS adout',
            'tool.tpl',
            'tool.spl',
            'NULL AS fpl',
            'tool.coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Метчик
    'OsevMet' => [
        'tables' => [
            'mz_tl_OsevMet AS tool' => [ 'mz_tl_Kind AS kind ON kind.id=tool.kind' ],
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'tool.d1',
            'tool.d2',
            'NULL AS d3',
            'NULL AS r',
            'NULL AS cf',
            'tool.l1',
            'tool.l2',
            'NULL AS l3',
            'NULL AS l4',
            'tool.ap',
            'NULL AS ar',
            'NULL AS z',
            'NULL AS purpose',
            'kind.label AS kind',
            'NULL AS angel',
            'tool.thread',
            'tool.pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'NULL AS adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'NULL AS adout',
            'NULL AS tpl',
            'NULL AS spl',
            'NULL AS fpl',
            'NULL AS coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient'
        ]
    ],
    
    // Пластина осевая
    'OsevPl' => [
        'tables' => [
            'mz_tl_OsevPl AS tool' => null,
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'NULL AS d1',
            'NULL AS d2',
            'NULL AS d3',
            'tool.r',
            'NULL AS cf',
            'NULL AS l1',
            'NULL AS l2',
            'NULL AS l3',
            'NULL AS l4',
            'NULL AS ap',
            'NULL AS ar',
            'NULL AS z',
            'tool.purpose',
            'NULL AS kind',
            'NULL AS angle',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'NULL AS adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'NULL AS adout',
            'tool.tpl',
            'tool.spl',
            'NULL AS fpl',
            'NULL AS coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Система расточная // !!! нет параметров
    //'RastSyst' => [
    //],
    // Оснастка расточная  // !!! нет параметров
    //'RastOsn' => [
    //],

    // Пластина расточная
    'RastPl' => [
        'tables' => [
            'mz_tl_RastPl AS tool' => [ 'mz_tl_TurnToolKind AS kind ON kind.id=tool.kind' ],
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'NULL AS d1',
            'NULL AS d2',
            'NULL AS d3',
            'tool.r',
            'NULL AS cf',
            'NULL AS l1',
            'NULL AS l2',
            'NULL AS l3',
            'NULL AS l4',
            'NULL AS ap',
            'NULL AS ar',
            'NULL AS z',
            'NULL AS purpose',
            'kind.label AS kind',
            'tool.ang AS angle',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'NULL AS adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'NULL AS adout',
            'tool.tpl',
            'tool.spl',
            'tool.fpl',
            'NULL AS coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Специнструмент осевой // !!! нет параметров
    //'OsevSpec' => [
    //],
    
    // Державка токарная
    'TokDer' => [
        'tables' => [
            'mz_tl_TokDer AS tool' => [ 'mz_tl_TurnToolKind AS kind ON kind.id=tool.kind' ],
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'NULL AS d1',
            'NULL AS d2',
            'NULL AS d3',
            'NULL AS r',
            'NULL AS cf',
            'tool.l1',
            'NULL AS l2',
            'NULL AS l3',
            'tool.l4',
            'NULL AS ap',
            'tool.ar',
            'NULL AS z',
            'NULL AS purpose',
            'kind.label AS kind',
            'tool.ang AS angle',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'NULL AS adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'tool.adout',
            'NULL AS tpl',
            'NULL AS spl',
            'tool.fpl',
            'NULL AS coolin',
            'NULL AS t',
            'tool.kr',
            'tool.f1',
            'tool.dmin',
            'tool.purpose1 AS purpout',
            'tool.purpose2 AS purpin',
            "CONCAT(CASE WHEN tool.type1 IS NOT NULL THEN '1' ELSE '.' END,CASE WHEN tool.type2 IS NOT NULL THEN '1' ELSE '.' END,CASE WHEN tool.type3 IS NOT NULL THEN '1' ELSE '.' END,CASE WHEN tool.type4 IS NOT NULL THEN '1' ELSE '.' END,CASE WHEN tool.type5 IS NOT NULL THEN '1' ELSE '.' END,CASE WHEN tool.type6 IS NOT NULL THEN '1' ELSE '.' END,CASE WHEN tool.type7 IS NOT NULL THEN '1' ELSE '.' END,CASE WHEN tool.type8 IS NOT NULL THEN '1' ELSE '.' END,CASE WHEN tool.type9 IS NOT NULL THEN '1' ELSE '.' END) as purptok",
            'tool.adin AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Резец монолитный
    'TokRezMon' => [
        'tables' => [
            'mz_tl_TokRezMon AS tool' => [ 'mz_tl_TurnToolKind AS kind ON kind.id=tool.kind' ],
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'NULL AS d1',
            'NULL AS d2',
            'NULL AS d3',
            'NULL AS r',
            'NULL AS cf',
            'tool.l1',
            'NULL AS l2',
            'NULL AS l3',
            'tool.l4',
            'tool.ap',
            'tool.ar',
            'NULL AS z',
            'NULL AS purpose',
            'kind.label AS kind',
            'NULL AS angle',
            'tool.thread',
            'NULL AS pitch',
            'tool.pmin',
            'tool.pmax',
            'NULL AS adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'tool.adout',
            'NULL AS tpl',
            'NULL AS spl',
            'NULL AS fpl',
            'NULL AS coolin',
            'NULL AS t',
            'tool.kr',
            'tool.f1',
            'tool.dmin',
            'tool.purpose1 AS purpout',
            'tool.purpose2 AS purpin',
            "CONCAT(CASE WHEN tool.type1 IS NOT NULL THEN '1' ELSE '.' END,CASE WHEN tool.type2 IS NOT NULL THEN '1' ELSE '.' END,CASE WHEN tool.type3 IS NOT NULL THEN '1' ELSE '.' END,CASE WHEN tool.type4 IS NOT NULL THEN '1' ELSE '.' END,CASE WHEN tool.type5 IS NOT NULL THEN '1' ELSE '.' END,CASE WHEN tool.type6 IS NOT NULL THEN '1' ELSE '.' END,CASE WHEN tool.type7 IS NOT NULL THEN '1' ELSE '.' END,CASE WHEN tool.type8 IS NOT NULL THEN '1' ELSE '.' END,CASE WHEN tool.type9 IS NOT NULL THEN '1' ELSE '.' END) as purptok",
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Пластина токарная
    'TokPl' => [
        'tables' => [
            'mz_tl_TokPl AS tool' => [ 'mz_tl_TurnToolKind AS kind ON kind.id=tool.kind' ],
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'NULL AS d1',
            'NULL AS d2',
            'NULL AS d3',
            'tool.r',
            'NULL AS cf',
            'NULL AS l1',
            'NULL AS l2',
            'NULL AS l3',
            'NULL AS l4',
            'tool.ap',
            'NULL AS ar',
            'NULL AS z',
            'tool.purpose',
            'kind.label AS kind',
            'tool.ang AS angle',
            'tool.thread',
            'NULL AS pitch',
            'tool.pmin',
            'tool.pmax',
            'NULL AS adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'NULL AS adout',
            'tool.tpl',
            'tool.spl',
            'tool.fpl',
            'NULL AS coolin',
            'NULL AS t',
            'tool.kr',
            'tool.f1',
            'tool.dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            "CONCAT(CASE WHEN tool.type1 IS NOT NULL THEN '1' ELSE '.' END,CASE WHEN tool.type2 IS NOT NULL THEN '1' ELSE '.' END,CASE WHEN tool.type3 IS NOT NULL THEN '1' ELSE '.' END,CASE WHEN tool.type4 IS NOT NULL THEN '1' ELSE '.' END,CASE WHEN tool.type5 IS NOT NULL THEN '1' ELSE '.' END,CASE WHEN tool.type6 IS NOT NULL THEN '1' ELSE '.' END,CASE WHEN tool.type7 IS NOT NULL THEN '1' ELSE '.' END,CASE WHEN tool.type8 IS NOT NULL THEN '1' ELSE '.' END,CASE WHEN tool.type9 IS NOT NULL THEN '1' ELSE '.' END) as purptok",
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Специнструмент токарный // !!! нет параметров
    //'TokSpec' => [
    //],

    // Многоцелевой токарный
    'TokMnogo' => [
        'tables' => [
            'mz_tl_TokMnogo AS tool' => [ 'mz_tl_TurnToolKind AS kind ON kind.id=tool.kind' ],
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'NULL AS d1',
            'tool.d2',
            'NULL AS d3',
            'NULL AS r',
            'NULL AS cf',
            'tool.l1',
            'NULL AS l2',
            'NULL AS l3',
            'NULL AS l4',
            'NULL AS ap',
            'NULL AS ar',
            'NULL AS z',
            'NULL AS purpose',
            'kind.label AS kind',
            'NULL AS angle',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'tool.adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'tool.adout',
            'NULL AS tpl',
            'NULL AS spl',
            'NULL AS fpl',
            'NULL AS coolin',
            'NULL AS t',
            'tool.kr',
            'tool.f1',
            'tool.dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Державка накатки
    'NakDer' => [
        'tables' => [
            'mz_tl_NakDer AS tool' => null,
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'NULL AS d1',
            'NULL AS d2',
            'NULL AS d3',
            'NULL AS r',
            'NULL AS cf',
            'tool.l1 AS l1',
            'NULL AS l2',
            'NULL AS l3',
            'NULL AS l4',
            'NULL AS ap',
            'NULL AS ar',
            'NULL AS z',
            'NULL AS purpose',
            'NULL AS kind',
            'NULL AS angle',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'NULL AS adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'tool.adout AS adout',
            'NULL AS tpl',
            'NULL AS spl',
            'NULL AS fpl',
            'NULL AS coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'CAST(tool.roll AS TEXT) AS inserts',
            'CAST(tool.roll_count AS INTEGER) AS icount',
            'CAST(tool.regmin AS REAL) AS regmin',
            'CAST(tool.regmax AS REAL) AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Ролик накатки
    'NakRoll' => [
        'tables' => [
            'mz_tl_NakRoll AS tool' => null,
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'tool.d AS d',
            'NULL AS d1',
            'NULL AS d2',
            'NULL AS d3',
            'NULL AS r',
            'NULL AS cf',
            'NULL AS l1',
            'NULL AS l2',
            'NULL AS l3',
            'NULL AS l4',
            'NULL AS ap',
            'NULL AS ar',
            'NULL AS z',
            'NULL AS purpose',
            'NULL AS kind',
            'NULL AS angle',
            'NULL AS thread',
            'tool.pitch AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'NULL AS adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'NULL AS adout',
            'NULL AS tpl',
            'tool.roll AS spl',
            'tool.type AS fpl',
            'NULL AS coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],

    // Цанга
    'OsnFrTsan' => [
        'tables' => [
            'mz_tl_OsnFrTsan AS tool' => null,
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'NULL AS d1',
            'tool.d2',
            'NULL AS d3',
            'NULL AS r',
            'NULL AS cf',
            'tool.l1',
            'NULL AS l2',
            'NULL AS l3',
            'NULL AS l4',
            'NULL AS ap',
            'NULL AS ar',
            'NULL AS z',
            'NULL AS purpose',
            'NULL AS kind',
            'NULL AS angle',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'NULL AS adin',
            'tool.adinmin AS adimin',
            'tool.adinmax AS adimax',
            'tool.adout',
            'NULL AS tpl',
            'NULL AS spl',
            'NULL AS fpl',
            'tool.coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Удлинитель
    'OsnFrUdl' => [
        'tables' => [
            'mz_tl_OsnFrUdl AS tool' => null,
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'NULL AS d1',
            'tool.d2',
            'NULL AS d3',
            'NULL AS r',
            'NULL AS cf',
            'tool.l1',
            'NULL AS l2',
            'NULL AS l3',
            'NULL AS l4',
            'NULL AS ap',
            'NULL AS ar',
            'NULL AS z',
            'NULL AS purpose',
            'NULL AS kind',
            'NULL AS angle',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'tool.adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'tool.adout',
            'NULL AS tpl',
            'NULL AS spl',
            'NULL AS fpl',
            'NULL AS coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],

    // Патрон
    'OsnFrPatr' => [
        'tables' => [
            'mz_tl_OsnFrPatr AS tool' => null,
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'NULL AS d1',
            'tool.d2',
            'tool.d3',
            'NULL AS r',
            'NULL AS cf',
            'tool.l1',
            'tool.l2',
            'NULL AS l3',
            'NULL AS l4',
            'NULL AS ap',
            'NULL AS ar',
            'NULL AS z',
            'NULL AS purpose',
            'NULL AS kind',
            'NULL AS angle',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'tool.adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'tool.adout',
            'NULL AS tpl',
            'NULL AS spl',
            'NULL AS fpl',
            'NULL AS coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Базовый держатель
    'OsnFrBazDer' => [
        'tables' => [
            'mz_tl_OsnFrBazDer AS tool' => null,
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'NULL AS d1',
            'tool.d2',
            'tool.d3',
            'NULL AS r',
            'NULL AS cf',
            'tool.l1',
            'tool.l2',
            'NULL AS l3',
            'NULL AS l4',
            'NULL AS ap',
            'NULL AS ar',
            'NULL AS z',
            'NULL AS purpose',
            'NULL AS kind',
            'NULL AS angle',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'tool.adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'tool.adout',
            'NULL AS tpl',
            'NULL AS spl',
            'NULL AS fpl',
            'NULL AS coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Переходник
    'OsnFrPer' => [
        'tables' => [
            'mz_tl_OsnFrPer AS tool' => null,
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'NULL AS d1',
            'tool.d2',
            'tool.d3',
            'NULL AS r',
            'NULL AS cf',
            'tool.l1',
            'tool.l2',
            'NULL AS l3',
            'NULL AS l4',
            'NULL AS ap',
            'NULL AS ar',
            'NULL AS z',
            'NULL AS purpose',
            'NULL AS kind',
            'NULL AS angle',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'tool.adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'tool.adout',
            'NULL AS tpl',
            'NULL AS spl',
            'NULL AS fpl',
            'NULL AS coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Оправка
    'OsnFrOpr' => [
        'tables' => [
            'mz_tl_OsnFrPer AS tool' => null,
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'NULL AS d1',
            'tool.d2',
            'tool.d3',
            'NULL AS r',
            'NULL AS cf',
            'tool.l1',
            'tool.l2',
            'NULL AS l3',
            'NULL AS l4',
            'NULL AS ap',
            'NULL AS ar',
            'NULL AS z',
            'NULL AS purpose',
            'NULL AS kind',
            'NULL AS angle',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'tool.adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'tool.adout',
            'NULL AS tpl',
            'NULL AS spl',
            'NULL AS fpl',
            'NULL AS coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Адаптеры
    'OsnTokAdap' => [
        'tables' => [
            'mz_tl_OsnTokAdap AS tool' => [ 'mz_tl_TurnToolKind AS kind ON kind.id=tool.kind' ],
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'NULL AS d1',
            'tool.d2',
            'NULL AS d3',
            'NULL AS r',
            'NULL AS cf',
            'tool.l1',
            'NULL AS l2',
            'NULL AS l3',
            'NULL AS l4',
            'NULL AS ap',
            'NULL AS ar',
            'NULL AS z',
            'NULL AS purpose',
            'kind.label AS kind',
            'tool.ang AS angle',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'tool.adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'tool.adout',
            'NULL AS tpl',
            'NULL AS spl',
            'NULL AS fpl',
            'NULL AS coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],
    
    // Блок QTN
    'OsnTokQTN' => [
        'tables' => [
            'mz_tl_OsnTokQTN AS tool' => [
                'mz_tl_TurnUnitKind AS kind ON kind.id=tool.kind',
                'mz_tl_CoolantType AS cool ON cool.id=tool.cool',
                'mz_tl_TurnUnitType AS type ON type.id=tool.type',
                'mz_tl_TurnUnitOrient AS orient ON orient.id=tool.orient',
            ],
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'NULL AS d1',
            'NULL AS d2',
            'NULL AS d3',
            'NULL AS r',
            'NULL AS cf',
            'NULL AS l1',
            'NULL AS l2',
            'NULL AS l3',
            'NULL AS l4',
            'NULL AS ap',
            'NULL AS ar',
            'NULL AS z',
            'NULL AS purpose',
            'kind.name  AS kind',
            'NULL AS angle',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'tool.adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'tool.adout',
            'NULL AS tpl',
            'NULL AS spl',
            'NULL AS fpl',
            'NULL AS coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'type.name AS tooltype',
            'cool.name AS cooltype',
            'tool.m AS m',
            'orient.name AS orient',
        ]
    ],
    
    // Блок Integrex i-150 // !!! нет параметров
    //'OsnTok150' => [
    //], 
    // Блок Integrex 300 // !!! нет параметров
    //'OsnTok300' => [
    //],
    // Оснастка станочная // !!! нет параметров
    //'OsnStan' => [
    //],
    // Запчасти // !!! нет параметров
    //'Zap' => [
    //],

    //  Борфреза
    'SlesBor' => [
        'tables' => [
            'mz_tl_SlesBor AS tool' => [ 'mz_tl_MillBorForm AS form ON form.id=tool.form' ],
            'mz_entity AS e' => null
        ],
        'rules'  => [ 'e.id=tool.id', 'e.active IS TRUE' ],
        'props'  => [
            'tool.id',
            'NULL AS d',
            'tool.d1 AS d1',
            'NULL AS d2',
            'NULL AS d3',
            'NULL AS r',
            'NULL AS cf',
            'NULL AS l1',
            'NULL AS l2',
            'NULL AS l3',
            'NULL AS l4',
            'NULL AS ap',
            'NULL AS ar',
            'NULL AS z',
            'NULL AS purpose',
            'NULL AS kind',
            'NULL AS angle',
            'NULL AS thread',
            'NULL AS pitch',
            'NULL AS pmin',
            'NULL AS pmax',
            'NULL AS adin',
            'NULL AS adimin',
            'NULL AS adimax',
            'NULL AS adout',
            'NULL AS tpl',
            'NULL AS spl',
            "form.label || ' • ' || form.name AS fpl",
            'NULL AS coolin',
            'NULL AS t',
            'NULL AS kr',
            'NULL AS f1',
            'NULL AS dmin',
            'NULL AS purpout',
            'NULL AS purpin',
            'NULL AS purptok',
            'NULL AS inserts',
            'NULL AS icount',
            'NULL AS regmin',
            'NULL AS regmax',
            'NULL AS tooltype',
            'NULL AS cooltype',
            'NULL AS m',
            'NULL AS orient',
        ]
    ],

];

$QueryPar2 = array_map(function($value){
    $Query = [];
    $Query[] = 'SELECT '. implode(',',$value['props']);
    $Query[] = 'FROM ' . implode(',',array_map(function($table,$joins){
        if($joins) $Joins =  implode(' ',array_map(function($join){
            return 'LEFT JOIN '. $join;
        },$joins));
        else $Joins = null;
        
        return $table .' '. $Joins;
    },array_keys($value['tables']),array_values($value['tables'])));
    $Query[] = 'WHERE ' . implode(' AND ',$value['rules']);
    return implode(' ',$Query);
},$Arr2);

// --- здесь можно сфорировать запрос и проверить его руками
$QueryPar2 = implode(' UNION ALL ',$QueryPar2);
//dump($QueryPar2);die();

// --- формирование запроса списка инструментов v2
$Query2 = [];
$Query2[] = 'SELECT ' . implode(',',[
    //'tool.id',
    'tool.hid,tool.name,tool.code,tool.code1,tool.ratio,tool.material,tool.info',
    'vendor.hid AS vendor_id',
    'tree.hid AS type_id',
            
    'params.d',
    'params.d1',
    'params.d2',
    'params.d3',
    'params.r',
    'CAST(params.cf AS real)',
    'params.l1',
    'params.l2',
    'params.l3',
    'params.l4',
    'params.ap',
    'params.ar',
    'params.z',
    'params.purpose',
    'params.kind',
    'params.angle',
    'params.thread',
    'params.pitch',
    'params.pmin',
    'params.pmax',
    'params.adin',
    'params.adimin',
    'params.adimax',
    'params.adout',
    'params.tpl',
    'params.spl',
    'params.fpl',
    'params.coolin',
    'params.t',
    'params.kr',
    'params.f1',
    'params.dmin',
    'params.purpout',
    'params.purpin',
    'params.purptok',
    'params.inserts',
    'params.icount',
    'params.regmin',
    'params.regmax',
    'params.tooltype',
    'params.cooltype',
    'params.m',
    'params.orient',
]);

$Query2[] = 'FROM mz_view_tl_Catalogue AS tool';
$Query2[] = 'LEFT JOIN mz_view_tl_Vendor AS vendor ON vendor.id=tool.vendor AND vendor.active=true';
$Query2[] = 'LEFT JOIN mz_view_Type AS type ON type.id=tool.type_id AND type.active=true';
$Query2[] = 'LEFT JOIN mz_view_tl_CatalogueTree AS tree ON tree.datatype_id=type.id AND tree.active=true';
$Query2[] = 'LEFT JOIN ('. $QueryPar2 .') as params ON params.id=tool.id';
$Query2[] = 'WHERE tool.active=true';
$Query2[] = 'ORDER BY tool.id';

$Query2 = implode(' ',$Query2);
//dump($Query2);die();

// --- полуение списка интсрументов
$Data2 = $Connect2->query($Query2);
$Data2 = array_combine(array_column($Data2,'hid'),$Data2);

// --- причесать материал PMKNSH
$_material = function($material){
    $Arr = array_map(function($code) use($material){
        //dump($material);
        if(strpos($material,$code.'1')!==false) return strtoupper($code);
        elseif(strpos($material,$code)!==false) return strtolower($code);
        else return '.';
    },['P','M','K','N','S','H']);
    return implode($Arr);
};

// --- причесать справочник
$Props = kernel\Ide\Datamodel::instance('/Tilda/Tool/Tool')->Props;
$Data2 = array_map(function($value) use($_material,$Props){
    // ---  добавить нули к real
    array_map(function($code,$val) use(&$value,$Props){
        if($Props[$code]['type'] === 'real') $value[$code] = $value[$code] ? number_format($val,4,'.','') : $val;
    },array_keys($value),array_values($value));
    
    if($value['material']) $value['material'] = $_material($value['material']);
    return $value;
},$Data2);
//dump($Data2);die();



// --- --- --- --- ---
// --- --- --- --- ---
// --- --- --- --- ---
$Arr4 = [
    'tables' => [
        'Tilda_Tool_Tool AS tool' => [
            'Tilda_Tool_Type AS type ON type.id=tool.type_id',
            'Tilda_Tool_Vendor AS vendor ON vendor.id=tool.vendor_id',
        ],
    ],
    'rules'  => [ 'tool.active IS TRUE' ],
    'props'  => [
        'tool.hid,tool.name,tool.code,tool.code1,tool.ratio,tool.material,tool.info',
        'vendor.hid AS vendor_id',
        'type.hid AS type_id',
                
        'tool.d',
        'tool.d1',
        'tool.d2',
        'tool.d3',
        'tool.r',
        'tool.cf',
        'tool.l1',
        'tool.l2',
        'tool.l3',
        'tool.l4',
        'tool.ap',
        'tool.ar',
        'tool.z',
        'tool.purpose',
        'tool.kind',
        'tool.angle',
        'tool.thread',
        'tool.pitch',
        'tool.pmin',
        'tool.pmax',
        'tool.adin',
        'tool.adimin',
        'tool.adimax',
        'tool.adout',
        'tool.tpl',
        'tool.spl',
        'tool.fpl',
        'tool.coolin',
        'tool.t',
        'tool.kr',
        'tool.f1',
        'tool.dmin',
        'tool.purpout',
        'tool.purpin',
        'tool.purptok',
        'tool.inserts',
        'tool.icount',
        'tool.regmin',
        'tool.regmax',
        'tool.tooltype',
        'tool.cooltype',
        'tool.m',
        'tool.orient',
    ]
];

$Query4 = array_map(function($value){
    $Query = [];
    $Query[] = 'SELECT '. implode(',',$value['props']);
    $Query[] = 'FROM ' . implode(',',array_map(function($table,$joins){
        if($joins) $Joins =  implode(' ',array_map(function($join){
            return 'LEFT JOIN '. $join;
        },$joins));
        else $Joins = null;
        
        return $table .' '. $Joins;
    },array_keys($value['tables']),array_values($value['tables'])));
    $Query[] = 'WHERE ' . implode(' AND ',$value['rules']);
    $Query[] = 'ORDER BY tool.id';
    return implode(' ',$Query);
},[$Arr4]);
$Query4 = $Query4[0];
//dump($Query4);die();

$Data4 = $Connect4->query($Query4);
$Data4 = array_combine(array_column($Data4,'hid'),$Data4);
//dump($Data4);die();


// --- --- --- --- ---
// --- --- --- --- ---
// --- --- --- --- ---
// --- NEW ---
$New = array_diff_key($Data2,$Data4);
//dump($New);die();

if(count($New)){
    $New = array_map(function($value){
        $value['type_id'] = $value['type_id'] ? '('.db\Cql::select('/Tilda/Tool/Type')->prop('id')->rule('hid',$value['type_id'])->Query.')' : null;
        $value['vendor_id'] = $value['vendor_id'] ? '('.db\Cql::select('/Tilda/Tool/Vendor')->prop('id')->rule('hid',$value['vendor_id'])->Query.')' : null;
        return $value;
    },$New);
    //dump($New);die();
    
    $QueryNew = db\Cql::insert('/Tilda/Tool/Tool')->valuesArr($New);
    //dump($QueryNew->Query);
    $Connect4->query($QueryNew);
}



// --- --- --- --- ---
// --- --- --- --- ---
// --- --- --- --- ---
// --- OLD ---
$Old = array_intersect_key($Data2,$Data4);
$Old = array_filter($Old,function($value) use($Data4){
    $Key = $value['hid'];
    
    /*if(array_diff($value,$Data4[$Key]) || array_diff($Data4[$Key],$value)){
        dump(array_diff($value,$Data4[$Key]));
        dump(array_diff($Data4[$Key],$value));
        dump($value['info']);
        dump($Data4[$Key]['info']);
        dump($value,'data2');
        dump($Data4[$Key],'data4');
        die();
    }*/
    
    return array_diff($value,$Data4[$Key]) || array_diff($Data4[$Key],$value);
});
//dump($Old);die();

if(count($Old)){
    $Old = array_map(function($value){
        $value['type_id'] = $value['type_id'] ? '('.db\Cql::select('/Tilda/Tool/Type')->prop('id')->rule('hid',$value['type_id'])->Query.')' : null;
        $value['vendor_id'] = $value['vendor_id'] ? '('.db\Cql::select('/Tilda/Tool/Vendor')->prop('id')->rule('hid',$value['vendor_id'])->Query.')' : null;
        return $value;
    },$Old);
    //dump($Old);die();
    
    $QueriesOld = array_map(function($value){
        return db\Cql::update('/Tilda/Tool/Tool')->values($value)->rule('hid',$value['hid'])->Query;
    },$Old);
    //dump($QueriesOld);die();
    $Connect4->exec($QueriesOld);
}
?>